"""Add extra idv columns to detached_award_procurement table

Revision ID: 63fa01eb7d08
Revises: 5cb2560ae8e6
Create Date: 2022-08-08 13:20:18.394496

"""

# revision identifiers, used by Alembic.
revision = '63fa01eb7d08'
down_revision = '5cb2560ae8e6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detached_award_procurement', sa.Column('idv_number_of_offers_received', sa.Text(), nullable=True))
    op.add_column('detached_award_procurement', sa.Column('idv_type_set_aside', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detached_award_procurement', 'idv_type_set_aside')
    op.drop_column('detached_award_procurement', 'idv_number_of_offers_received')

